server:
    build: ./Dockerfiles
    dockerfile: Server
    command: node server/src/main.js
    ports:
        - 3100:3100
    environment:
        - NODE_ENV=test
        - VIRTUAL_PORT=3100
    volumes:
        - .:/usr/6bin
    tty: true

tests:
    build: ./Dockerfiles
    dockerfile: Test
    command: node tests/index.js
    links:
        - server
    environment:
        - NODE_ENV=test
    volumes:
        - ./:/usr/6bin/
    tty: true
