server:
    build: ./Dockerfiles
    dockerfile: Server
    command: node server/src/main.js
    ports:
        - 3000:3000
    environment:
        - NODE_ENV=production
        - VIRTUAL_PORT=3000
    volumes:
        - .:/usr/6bin
    tty: true
    restart: always