server:
    build: ./
    command: nodemon --watch server server/src/main.js
    ports:
        - 3000:3000
    environment:
        - NODE_ENV=development
    volumes:
        - .:/usr/6bin
    tty: true